plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# SEO Stuff
author: Mike Stone 
description: Mike's Personal Blog
lang: en
locale: en_US
url: "https://mikestone.me"
baseurl: "https://mikestone.me"
paginate: 10

# RSS feeds
feed:
  posts_limit: 20
