plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Mike Stone 
description: Mike's Personal Blog
lang: en
locale: en_US
url: "https://mikestone.me"
baseurl: 

# RSS feeds
feed:
  posts_limit: 20
