plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Mike Stone
description: Mostly The Lonely Howls Of Mike Baying His Ideological Purity At The Moon
lang: en
locale: en_US
url: "https://mikestone.me"
baseurl:

# RSS feeds
feed:
  posts_limit: 20

# Netlify redirects
include:
  - _redirects
